### ISSUE TITLE
Destek reposundan farki?

### ISSUE THREAD

**Issue by tarikguney** [gelis-tr-io/soru-cevap#1]
@selmansamet, bu reponun destek reposundan farki tam olarak nedir?

**Comment by sametcodes** [comment]
@tarikguney Destek reposunu daha çok *grupla ilgili* olan soru, istek ve öneriler şeklinde düşünmüştüm. Bundan bağımsız olarak, teknik soruların ve cevapların barınabileceği bir soru-cevap reposuna ihtiyaç olduğunu düşünüyorum.

**Comment by tarikguney** [comment]
Eğer öyle anlaşılıyorsa, o zaman dediğin gibi kalsın.
